name: test suite
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout test data repo
        uses: actions/checkout@v4
        with:
          repository: OpenBeta/open-tick-list
          path: test-data/open-tick-list
          ref: 98181c3dcfb27f7fc767db37291c45dda1be3811

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo test --all-features
