name: test suite
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout test data repo
        uses: actions/checkout@v4
        with:
          repository: OpenBeta/open-tick-list
          path: test-data/open-tick-list
          ref: 98181c3dcfb27f7fc767db37291c45dda1be3811

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo test --all-features

        # Coverage with https://github.com/taiki-e/cargo-llvm-cov/
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Upload cargo-llvl-cov coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: lcov.info
          fail_ci_if_error: true
